src/utils/sdkmarcos.h usr/include/kysdk/kysdk-base
src/utils/kerr.h usr/include/kysdk/kysdk-base
src/utils/cstring-extension.h usr/include/kysdk/kysdk-base
src/utils/kyutils.h usr/include/kysdk/kysdk-base
src/utils/data-structure/linklist/skip_linklist/skip_linklist.h usr/include/kysdk/kysdk-base
src/utils/data-structure/linklist/listdata.h usr/include/kysdk/kysdk-base
development-files/kysdk-utils.pc usr/share/pkgconfig/
